// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service/test_a/test_a.proto

package grpc_demo_go.protobuf.service.test_a;

public final class TestAService {
  private TestAService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EchoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc_demo_go.protobuf.service.test_a.EchoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * 示例输出请求
   * </pre>
   *
   * Protobuf type {@code grpc_demo_go.protobuf.service.test_a.EchoRequest}
   */
  public  static final class EchoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc_demo_go.protobuf.service.test_a.EchoRequest)
      EchoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EchoRequest.newBuilder() to construct.
    private EchoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EchoRequest() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EchoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc_demo_go.protobuf.service.test_a.TestAService.internal_static_grpc_demo_go_protobuf_service_test_a_EchoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc_demo_go.protobuf.service.test_a.TestAService.internal_static_grpc_demo_go_protobuf_service_test_a_EchoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest.class, grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest)) {
        return super.equals(obj);
      }
      grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest other = (grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 示例输出请求
     * </pre>
     *
     * Protobuf type {@code grpc_demo_go.protobuf.service.test_a.EchoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc_demo_go.protobuf.service.test_a.EchoRequest)
        grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc_demo_go.protobuf.service.test_a.TestAService.internal_static_grpc_demo_go_protobuf_service_test_a_EchoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc_demo_go.protobuf.service.test_a.TestAService.internal_static_grpc_demo_go_protobuf_service_test_a_EchoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest.class, grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest.Builder.class);
      }

      // Construct using grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc_demo_go.protobuf.service.test_a.TestAService.internal_static_grpc_demo_go_protobuf_service_test_a_EchoRequest_descriptor;
      }

      @java.lang.Override
      public grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest getDefaultInstanceForType() {
        return grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest build() {
        grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest buildPartial() {
        grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest result = new grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest) {
          return mergeFrom((grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest other) {
        if (other == grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc_demo_go.protobuf.service.test_a.EchoRequest)
    }

    // @@protoc_insertion_point(class_scope:grpc_demo_go.protobuf.service.test_a.EchoRequest)
    private static final grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest();
    }

    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EchoRequest>
        PARSER = new com.google.protobuf.AbstractParser<EchoRequest>() {
      @java.lang.Override
      public EchoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EchoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EchoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EchoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc_demo_go.protobuf.service.test_a.TestAService.EchoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EchoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc_demo_go.protobuf.service.test_a.EchoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
     */
    boolean hasMeta();
    /**
     * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
     */
    grpc_demo_go.protobuf.message.MetaMessage.Meta getMeta();
    /**
     * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
     */
    grpc_demo_go.protobuf.message.MetaMessage.MetaOrBuilder getMetaOrBuilder();

    /**
     * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
     */
    boolean hasData();
    /**
     * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
     */
    grpc_demo_go.protobuf.message.EchoMessage.Echo getData();
    /**
     * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
     */
    grpc_demo_go.protobuf.message.EchoMessage.EchoOrBuilder getDataOrBuilder();
  }
  /**
   * <pre>
   * 示例输出响应
   * </pre>
   *
   * Protobuf type {@code grpc_demo_go.protobuf.service.test_a.EchoResponse}
   */
  public  static final class EchoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc_demo_go.protobuf.service.test_a.EchoResponse)
      EchoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EchoResponse.newBuilder() to construct.
    private EchoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EchoResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EchoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              grpc_demo_go.protobuf.message.MetaMessage.Meta.Builder subBuilder = null;
              if (meta_ != null) {
                subBuilder = meta_.toBuilder();
              }
              meta_ = input.readMessage(grpc_demo_go.protobuf.message.MetaMessage.Meta.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(meta_);
                meta_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              grpc_demo_go.protobuf.message.EchoMessage.Echo.Builder subBuilder = null;
              if (data_ != null) {
                subBuilder = data_.toBuilder();
              }
              data_ = input.readMessage(grpc_demo_go.protobuf.message.EchoMessage.Echo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(data_);
                data_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc_demo_go.protobuf.service.test_a.TestAService.internal_static_grpc_demo_go_protobuf_service_test_a_EchoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc_demo_go.protobuf.service.test_a.TestAService.internal_static_grpc_demo_go_protobuf_service_test_a_EchoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse.class, grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse.Builder.class);
    }

    public static final int META_FIELD_NUMBER = 1;
    private grpc_demo_go.protobuf.message.MetaMessage.Meta meta_;
    /**
     * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
     */
    public boolean hasMeta() {
      return meta_ != null;
    }
    /**
     * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
     */
    public grpc_demo_go.protobuf.message.MetaMessage.Meta getMeta() {
      return meta_ == null ? grpc_demo_go.protobuf.message.MetaMessage.Meta.getDefaultInstance() : meta_;
    }
    /**
     * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
     */
    public grpc_demo_go.protobuf.message.MetaMessage.MetaOrBuilder getMetaOrBuilder() {
      return getMeta();
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private grpc_demo_go.protobuf.message.EchoMessage.Echo data_;
    /**
     * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
     */
    public boolean hasData() {
      return data_ != null;
    }
    /**
     * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
     */
    public grpc_demo_go.protobuf.message.EchoMessage.Echo getData() {
      return data_ == null ? grpc_demo_go.protobuf.message.EchoMessage.Echo.getDefaultInstance() : data_;
    }
    /**
     * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
     */
    public grpc_demo_go.protobuf.message.EchoMessage.EchoOrBuilder getDataOrBuilder() {
      return getData();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (meta_ != null) {
        output.writeMessage(1, getMeta());
      }
      if (data_ != null) {
        output.writeMessage(2, getData());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (meta_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMeta());
      }
      if (data_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse)) {
        return super.equals(obj);
      }
      grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse other = (grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse) obj;

      if (hasMeta() != other.hasMeta()) return false;
      if (hasMeta()) {
        if (!getMeta()
            .equals(other.getMeta())) return false;
      }
      if (hasData() != other.hasData()) return false;
      if (hasData()) {
        if (!getData()
            .equals(other.getData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMeta()) {
        hash = (37 * hash) + META_FIELD_NUMBER;
        hash = (53 * hash) + getMeta().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 示例输出响应
     * </pre>
     *
     * Protobuf type {@code grpc_demo_go.protobuf.service.test_a.EchoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc_demo_go.protobuf.service.test_a.EchoResponse)
        grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc_demo_go.protobuf.service.test_a.TestAService.internal_static_grpc_demo_go_protobuf_service_test_a_EchoResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc_demo_go.protobuf.service.test_a.TestAService.internal_static_grpc_demo_go_protobuf_service_test_a_EchoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse.class, grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse.Builder.class);
      }

      // Construct using grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (metaBuilder_ == null) {
          meta_ = null;
        } else {
          meta_ = null;
          metaBuilder_ = null;
        }
        if (dataBuilder_ == null) {
          data_ = null;
        } else {
          data_ = null;
          dataBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc_demo_go.protobuf.service.test_a.TestAService.internal_static_grpc_demo_go_protobuf_service_test_a_EchoResponse_descriptor;
      }

      @java.lang.Override
      public grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse getDefaultInstanceForType() {
        return grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse.getDefaultInstance();
      }

      @java.lang.Override
      public grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse build() {
        grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse buildPartial() {
        grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse result = new grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse(this);
        if (metaBuilder_ == null) {
          result.meta_ = meta_;
        } else {
          result.meta_ = metaBuilder_.build();
        }
        if (dataBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse) {
          return mergeFrom((grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse other) {
        if (other == grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse.getDefaultInstance()) return this;
        if (other.hasMeta()) {
          mergeMeta(other.getMeta());
        }
        if (other.hasData()) {
          mergeData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private grpc_demo_go.protobuf.message.MetaMessage.Meta meta_;
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc_demo_go.protobuf.message.MetaMessage.Meta, grpc_demo_go.protobuf.message.MetaMessage.Meta.Builder, grpc_demo_go.protobuf.message.MetaMessage.MetaOrBuilder> metaBuilder_;
      /**
       * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
       */
      public boolean hasMeta() {
        return metaBuilder_ != null || meta_ != null;
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
       */
      public grpc_demo_go.protobuf.message.MetaMessage.Meta getMeta() {
        if (metaBuilder_ == null) {
          return meta_ == null ? grpc_demo_go.protobuf.message.MetaMessage.Meta.getDefaultInstance() : meta_;
        } else {
          return metaBuilder_.getMessage();
        }
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
       */
      public Builder setMeta(grpc_demo_go.protobuf.message.MetaMessage.Meta value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          meta_ = value;
          onChanged();
        } else {
          metaBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
       */
      public Builder setMeta(
          grpc_demo_go.protobuf.message.MetaMessage.Meta.Builder builderForValue) {
        if (metaBuilder_ == null) {
          meta_ = builderForValue.build();
          onChanged();
        } else {
          metaBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
       */
      public Builder mergeMeta(grpc_demo_go.protobuf.message.MetaMessage.Meta value) {
        if (metaBuilder_ == null) {
          if (meta_ != null) {
            meta_ =
              grpc_demo_go.protobuf.message.MetaMessage.Meta.newBuilder(meta_).mergeFrom(value).buildPartial();
          } else {
            meta_ = value;
          }
          onChanged();
        } else {
          metaBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
       */
      public Builder clearMeta() {
        if (metaBuilder_ == null) {
          meta_ = null;
          onChanged();
        } else {
          meta_ = null;
          metaBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
       */
      public grpc_demo_go.protobuf.message.MetaMessage.Meta.Builder getMetaBuilder() {
        
        onChanged();
        return getMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
       */
      public grpc_demo_go.protobuf.message.MetaMessage.MetaOrBuilder getMetaOrBuilder() {
        if (metaBuilder_ != null) {
          return metaBuilder_.getMessageOrBuilder();
        } else {
          return meta_ == null ?
              grpc_demo_go.protobuf.message.MetaMessage.Meta.getDefaultInstance() : meta_;
        }
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Meta meta = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc_demo_go.protobuf.message.MetaMessage.Meta, grpc_demo_go.protobuf.message.MetaMessage.Meta.Builder, grpc_demo_go.protobuf.message.MetaMessage.MetaOrBuilder> 
          getMetaFieldBuilder() {
        if (metaBuilder_ == null) {
          metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              grpc_demo_go.protobuf.message.MetaMessage.Meta, grpc_demo_go.protobuf.message.MetaMessage.Meta.Builder, grpc_demo_go.protobuf.message.MetaMessage.MetaOrBuilder>(
                  getMeta(),
                  getParentForChildren(),
                  isClean());
          meta_ = null;
        }
        return metaBuilder_;
      }

      private grpc_demo_go.protobuf.message.EchoMessage.Echo data_;
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc_demo_go.protobuf.message.EchoMessage.Echo, grpc_demo_go.protobuf.message.EchoMessage.Echo.Builder, grpc_demo_go.protobuf.message.EchoMessage.EchoOrBuilder> dataBuilder_;
      /**
       * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
       */
      public boolean hasData() {
        return dataBuilder_ != null || data_ != null;
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
       */
      public grpc_demo_go.protobuf.message.EchoMessage.Echo getData() {
        if (dataBuilder_ == null) {
          return data_ == null ? grpc_demo_go.protobuf.message.EchoMessage.Echo.getDefaultInstance() : data_;
        } else {
          return dataBuilder_.getMessage();
        }
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
       */
      public Builder setData(grpc_demo_go.protobuf.message.EchoMessage.Echo value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          data_ = value;
          onChanged();
        } else {
          dataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
       */
      public Builder setData(
          grpc_demo_go.protobuf.message.EchoMessage.Echo.Builder builderForValue) {
        if (dataBuilder_ == null) {
          data_ = builderForValue.build();
          onChanged();
        } else {
          dataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
       */
      public Builder mergeData(grpc_demo_go.protobuf.message.EchoMessage.Echo value) {
        if (dataBuilder_ == null) {
          if (data_ != null) {
            data_ =
              grpc_demo_go.protobuf.message.EchoMessage.Echo.newBuilder(data_).mergeFrom(value).buildPartial();
          } else {
            data_ = value;
          }
          onChanged();
        } else {
          dataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = null;
          onChanged();
        } else {
          data_ = null;
          dataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
       */
      public grpc_demo_go.protobuf.message.EchoMessage.Echo.Builder getDataBuilder() {
        
        onChanged();
        return getDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
       */
      public grpc_demo_go.protobuf.message.EchoMessage.EchoOrBuilder getDataOrBuilder() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilder();
        } else {
          return data_ == null ?
              grpc_demo_go.protobuf.message.EchoMessage.Echo.getDefaultInstance() : data_;
        }
      }
      /**
       * <code>.grpc_demo_go.protobuf.message.Echo data = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc_demo_go.protobuf.message.EchoMessage.Echo, grpc_demo_go.protobuf.message.EchoMessage.Echo.Builder, grpc_demo_go.protobuf.message.EchoMessage.EchoOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              grpc_demo_go.protobuf.message.EchoMessage.Echo, grpc_demo_go.protobuf.message.EchoMessage.Echo.Builder, grpc_demo_go.protobuf.message.EchoMessage.EchoOrBuilder>(
                  getData(),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc_demo_go.protobuf.service.test_a.EchoResponse)
    }

    // @@protoc_insertion_point(class_scope:grpc_demo_go.protobuf.service.test_a.EchoResponse)
    private static final grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse();
    }

    public static grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EchoResponse>
        PARSER = new com.google.protobuf.AbstractParser<EchoResponse>() {
      @java.lang.Override
      public EchoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EchoResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EchoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EchoResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc_demo_go.protobuf.service.test_a.TestAService.EchoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_demo_go_protobuf_service_test_a_EchoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_demo_go_protobuf_service_test_a_EchoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_demo_go_protobuf_service_test_a_EchoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_demo_go_protobuf_service_test_a_EchoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033service/test_a/test_a.proto\022$grpc_demo" +
      "_go.protobuf.service.test_a\032\022message/ech" +
      "o.proto\032\022message/meta.proto\"\036\n\013EchoReque" +
      "st\022\017\n\007message\030\001 \001(\t\"t\n\014EchoResponse\0221\n\004m" +
      "eta\030\001 \001(\0132#.grpc_demo_go.protobuf.messag" +
      "e.Meta\0221\n\004data\030\002 \001(\0132#.grpc_demo_go.prot" +
      "obuf.message.Echo2z\n\007Greeter\022o\n\004Echo\0221.g" +
      "rpc_demo_go.protobuf.service.test_a.Echo" +
      "Request\0322.grpc_demo_go.protobuf.service." +
      "test_a.EchoResponse\"\000BBB\014TestAServiceZ#g" +
      "rpc-demo-go/protobuf/service/testA\242\002\014Tes" +
      "tAServiceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc_demo_go.protobuf.message.EchoMessage.getDescriptor(),
          grpc_demo_go.protobuf.message.MetaMessage.getDescriptor(),
        }, assigner);
    internal_static_grpc_demo_go_protobuf_service_test_a_EchoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_demo_go_protobuf_service_test_a_EchoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_demo_go_protobuf_service_test_a_EchoRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_grpc_demo_go_protobuf_service_test_a_EchoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_demo_go_protobuf_service_test_a_EchoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_demo_go_protobuf_service_test_a_EchoResponse_descriptor,
        new java.lang.String[] { "Meta", "Data", });
    grpc_demo_go.protobuf.message.EchoMessage.getDescriptor();
    grpc_demo_go.protobuf.message.MetaMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
